[package]
authors = {workspace = true}
edition = {workspace = true}
license = {workspace = true}
repository = {workspace = true}
description = "Typed high-level intermediate representation for Shackle"
name = "shackle-thir"
version = "0.1.0"

[dependencies]
derive_more = {workspace = true, features = [
  "deref",
  "deref_mut",
  "from",
  "into",
  "index",
  "unwrap",
  "try_unwrap",
]}
log = {workspace = true}
miette = {workspace = true}
rustc-hash = {workspace = true}
salsa = {workspace = true}
shackle-diagnostics = {workspace = true}
shackle-hir = {workspace = true}
shackle-syntax = {workspace = true}
shackle-ty = {workspace = true}
shackle-utils = {workspace = true}

[dev-dependencies]
expect-test = {workspace = true}

[lints]
workspace = true
