[workspace]
changelog_update = false # disable automatic changelog update

### DISABLE PACKAGES NOT READY FOR RELEASE ###
[[package]]
name = "shackle"
release = false

[[package]]
name = "shackle-cli"
release = false

[[package]]
name = "shackle-diagnostics"
release = false

[[package]]
name = "shackle-fmt"
release = false

[[package]]
name = "shackle-hir"
release = false

[[package]]
name = "shackle-ls"
git_only = true
publish = false

[[package]]
name = "shackle-syntax"
release = false

[[package]]
name = "shackle-thir"
release = false

[[package]]
name = "shackle-ty"
release = false

[[package]]
name = "shackle-utils"
release = false

[[package]]
name = "shackle-utils-derive"
release = false

[[package]]
name = "tree-sitter-datazinc"
release = false

[[package]]
name = "tree-sitter-eprime"
release = false

[[package]]
name = "tree-sitter-minizinc"
release = false
