[package]
name = "shackle-runtime"
version = "0.1.0"
authors = ["Jip J. Dekker <jip@dekker.one>"]
license = "MPL-2.0"

edition = "2021"

[dependencies]
bilge = "0.2.0"
varlen = { version = "0.1.2", features = ["macro"] }
