[package]
authors = {workspace = true}
edition = {workspace = true}
license = {workspace = true}
repository = {workspace = true}
description = "MiniZinc code formatting"
name = "shackle-fmt"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = {workspace = true}
rustc-hash = {workspace = true}
serde = {workspace = true}
shackle-diagnostics = {workspace = true}
shackle-syntax = {workspace = true}
stacker = {workspace = true}
streaming-iterator = {workspace = true}
tree-sitter = {workspace = true}
tree-sitter-minizinc = {workspace = true}

console = {version = "0.16.3", optional = true}
glob = {version = "0.3.3", optional = true}
miette = {workspace = true, optional = true}
similar = {version = "3.1.0", optional = true}

[dev-dependencies]
expect-test = {workspace = true}
glob = "0.3.3"
pretty_assertions = "1.4.1"
shackle-hir = {workspace = true}

[features]
fancy = ["console", "glob", "miette", "similar"]

[lints]
workspace = true
