[package]
name = "shackle"
version = "0.1.0"
edition = "2021"
authors = ["Jip J. Dekker <jip@dekker.one>"]

[dependencies]
miette = { version = "4.2.1" }
thiserror = "1.0.3"
tree-sitter = "0.20.6"
tree-sitter-minizinc = { path = "../../misc/tree-sitter-minizinc" }
