[package]
authors = {workspace = true}
edition = {workspace = true}
license = {workspace = true}
name = "shackle-ls"
version = "0.1.0"

[dependencies]
crossbeam-channel = "0.5.8"
env_logger = {workspace = true}
log = {workspace = true}
lsp-server = "0.9.0"
lsp-types = "0.97"
miette = {workspace = true}
serde_json = {workspace = true}
shackle-diagnostics = {path = "../shackle-diagnostics"}
shackle-fmt = {path = "../shackle-fmt"}
shackle-hir = {path = "../shackle-hir"}
shackle-syntax = {path = "../shackle-syntax"}
shackle-thir = {path = "../shackle-thir"}
shackle-ty = {path = "../shackle-ty"}
threadpool = "1.8.1"
# tree-sitter = { workspace = true }
# tree-sitter-minizinc = { path = "../../parsers/tree-sitter-minizinc" }

[dev-dependencies]
expect-test = "1.4.1"

[lints]
workspace = true
