[package]
authors = {workspace = true}
edition = {workspace = true}
license = {workspace = true}
repository = {workspace = true}
description = "Language server implementation for Shackle"
name = "shackle-ls"
version = "0.3.1"

[dependencies]
crossbeam-channel = "0.5.8"
env_logger = {workspace = true}
log = {workspace = true}
lsp-server = "0.10.0"
lsp-types = "0.97"
miette = {workspace = true}
serde_json = {workspace = true}
shackle-diagnostics = {workspace = true}
shackle-fmt = {workspace = true}
shackle-hir = {workspace = true}
shackle-syntax = {workspace = true}
shackle-thir = {workspace = true}
shackle-ty = {workspace = true}
threadpool = "1.8.1"
# tree-sitter = { workspace = true }
# tree-sitter-minizinc = { path = "../../parsers/tree-sitter-minizinc" }

[dev-dependencies]
expect-test = "1.4.1"

[lints]
workspace = true
