[package]
authors = {workspace = true}
edition = {workspace = true}
license = {workspace = true}
repository = {workspace = true}
description = "Diagnostic types and rendering support for Shackle"
name = "shackle-diagnostics"
version = "0.1.0"

[dependencies]
miette = {workspace = true}
serde_json = {workspace = true}
thiserror = "2.0.18"

[lints]
workspace = true
