[book]
authors = ["Jip J. Dekker"]
language = "en"
multilingual = false
src = "src"
title = "The Shackle Almanac"

[output.html]
additional-js = ["theme/mzn-highlight.js"]
# TODO: We use newer version (3.1+) of MathJax for the proofs. Remove custom "head.hbs" code when possible
mathjax-support = false

[preprocessor.mermaid]
command = "python utils/mermaid.py"
