[package]
name = "tree-sitter-eprime"
description = "Essence Prime grammar for tree-sitter"
version = "0.1.0"
authors = ["Jip J. Dekker <jip.dekker@monash.edu>"]
license = "MPL-2.0"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "eprime"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "git+https://github.com/shackle-rs/shackle.git"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.3"
