[package]
authors = {workspace = true}
edition = {workspace = true}
license = {workspace = true}
repository = {workspace = true}
description = "Type checking and inference support for Shackle"
name = "shackle-ty"
version = "0.1.0"

[dependencies]
log = {workspace = true}
rustc-hash = {workspace = true}
salsa = {workspace = true}
shackle-syntax = {workspace = true}
shackle-utils = {workspace = true}

[lints]
workspace = true
