name: Check Format

on: [push, pull_request]

env:
  RUST_CHANNEL: stable

jobs:
  check_format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Check formatting of Rust files
      - name: Install Rust toolchain
        run: |
          rustup toolchain install --profile minimal --component rustfmt --no-self-update ${{ env.RUST_CHANNEL }}
          rustup default ${{ env.RUST_CHANNEL }}
      - name: Run cargo check
        run: cargo fmt --all --check

      # Check formatting of other files
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install prettier
        run: npm ci
      - name: Run prettier
        run: npm run format:check
