name: Check Format

on: [push, pull_request]

jobs:
  check_format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Check formatting of Rust files
      - name: Install correct toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      # Check formatting of other files
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install prettier
        run: npm ci
      - name: Run prettier
        run: npm run format:check
