name: VS Code Extension

on:
  push:
    branches-ignore:
      - "dependabot/**"
      - "release-plz-*"
  pull_request:
  release:
    types: [published]

env:
  RUST_CHANNEL: "stable"
  MINIZINC_REF: "develop"

jobs:
  language-server:
    name: shackle-ls (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x64
          - os: ubuntu-24.04-arm
            target: linux-arm64
          - os: windows-latest
            target: win32-x64
          - os: windows-11-arm
            target: win32-arm64
          - os: macos-15-intel
            target: darwin-x64
          - os: macos-latest
            target: darwin-arm64
    steps:
      - uses: actions/checkout@v7
      - name: Checkout MiniZinc repo
        uses: actions/checkout@v7
        with:
          repository: MiniZinc/libminizinc
          path: minizinc
          ref: ${{ env.MINIZINC_REF }}
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          cache-target: release
          channel: ${{ env.RUST_CHANNEL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build shackle-ls
        run: |
          cargo install --root dist/ --path crates/shackle-ls
      - name: Copy MiniZinc standard library (Windows)
        if: startsWith(matrix.target, 'win32')
        run: |
          mkdir -p "dist/share/minizinc"
          Get-ChildItem -Path "minizinc/share/minizinc/std/" | Copy-Item -Destination "dist/share/minizinc/std/" -Recurse -Force
          Get-ChildItem -Path "share/minizinc/std/" | Copy-Item -Destination "dist/share/minizinc/std/" -Recurse -Force
      - name: Copy MiniZinc standard library (non-Windows)
        if: ${{ !startsWith(matrix.target, 'win32') }}
        run: |
          mkdir -p "dist/share/minizinc"
          rsync -av "minizinc/share/minizinc/std/" "dist/share/minizinc/std/"
          rsync -av "share/minizinc/std/" "dist/share/minizinc/std/"
      - name: Create tar archive for shackle-ls
        run: |
          tar -czf "${{ env.TAR_PREFIX }}-${{ matrix.target }}.tar.gz" -C dist/ bin share
        env:
          TAR_PREFIX: ${{ startsWith(github.event.release.tag_name, 'shackle-ls-v') && github.event.release.tag_name || format('shackle-ls-build{0}', github.run_id) }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          path: shackle-ls-*.tar.gz
          archive: false

  publish-language-server:
    name: Publish Language Server
    runs-on: ubuntu-latest
    needs: language-server
    permissions:
      contents: write
    if: startsWith(github.event.release.tag_name, 'shackle-ls-v')
    steps:
      - uses: actions/checkout@v7
      - name: Download shackle-ls build artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: shackle-ls-*
          merge-multiple: true
      - name: Add assets to release
        run: |
          for artifact in shackle-ls-*.tar.gz; do
            gh release upload ${GITHUB_REF_NAME#refs/tags/} "$artifact" --clobber
          done
        env:
          GH_TOKEN: ${{ github.token }}

  vscode-extension:
    name: VS Code Extension (${{ matrix.target }})
    runs-on: ubuntu-latest
    needs: language-server
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-x64
          - linux-arm64
          - win32-x64
          - win32-arm64
          - darwin-x64
          - darwin-arm64
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: npm
      - name: Sync version with language server
        run: |
          VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' crates/shackle-ls/Cargo.toml)
          npm version $VERSION --workspace minizinc --no-git-tag-version
      - name: Install dependencies
        run: npm ci --workspace minizinc --include-workspace-root
      - name: Run linter
        run: npm run vscode:lint
        continue-on-error: true
      - name: Bundle VS Code extension with esbuild
        run: npm run vscode:build
      - name: Download shackle-ls build artifact
        uses: actions/download-artifact@v8
        with:
          pattern: shackle-ls-*-${{ matrix.target }}.tar.gz
      - name: Bundle VS Code extension assets
        shell: bash
        run: |
          tar -xzf shackle-ls-*.tar.gz -C "editors/code/"
          cp "LICENSE" "editors/code/LICENSE"
      - name: Package VS Code extension
        run: npm run package:vsix -w minizinc -- --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: editors/code/*.vsix
          archive: false

  publish-extension:
    name: Publish VS Code Extension
    runs-on: ubuntu-latest
    needs: vscode-extension
    if: startsWith(github.event.release.tag_name, 'shackle-ls-v')
    environment:
      name: vscode-extension
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - name: Download VS Code extension artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: "*.vsix"
          path: editors/code
          merge-multiple: true
      - name: Publish release on Open VSX
        run: |
          npx ovsx publish --skip-duplicate --packagePath editors/code/*.vsix
        env:
          OVSX_PAT: ${{ secrets.OPEN_VSX_ACCESS }}
      - name: Authenticate with Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
      - name: Publish release on VS Code Marketplace
        run: |
          npx @vscode/vsce publish --azure-credential --skip-duplicate --packagePath editors/code/*.vsix
