[package]
authors = {workspace = true}
edition = {workspace = true}
license = {workspace = true}
name = "shackle"
version = "0.1.0"

[dependencies]
itertools = "0.15.0"
log = {workspace = true}
rustc-hash = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
shackle-diagnostics = {path = "../shackle-diagnostics"}
shackle-fmt = {path = "../shackle-fmt"}
shackle-hir = {path = "../shackle-hir"}
shackle-syntax = {path = "../shackle-syntax"}
shackle-thir = {path = "../shackle-thir"}
shackle-ty = {path = "../shackle-ty"}
shackle-utils = {path = "../shackle-utils"}
tempfile = "3.5.0"

[dev-dependencies]
expect-test = {workspace = true}
